# Generated by Django 3.2.16 on 2023-02-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0002_profile_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.TextField(null=True)),
                ('point', models.TextField(null=True)),
                ('unit_point', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('etc', models.TextField(null=True)),
                ('memo', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
